"""add checkresult latest index

Revision ID: 558d870f9035
Revises: b794db3040c8
Create Date: 2026-09-10 12:13:13.284685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '558d870f9035'
down_revision: Union[str, Sequence[str], None] = 'b794db3040c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_checkresult_endpoint_id'), table_name='checkresult')
    op.create_index('ix_checkresult_latest', 'checkresult', ['endpoint_id', sa.literal_column('checked_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checkresult_latest', table_name='checkresult')
    op.create_index(op.f('ix_checkresult_endpoint_id'), 'checkresult', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###
