"""add alert config and state

Revision ID: b794db3040c8
Revises: 54b9dac1d998
Create Date: 2026-09-08 18:22:20.464464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'b794db3040c8'
down_revision: Union[str, Sequence[str], None] = '54b9dac1d998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WEBHOOK', name='alertchannel'), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False), #type: ignore
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoint.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertconfig_endpoint_id'), 'alertconfig', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_alertconfig_user_id'), 'alertconfig', ['user_id'], unique=False)
    op.create_table('alertstate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('alert_sent', sa.Boolean(), nullable=False),
    sa.Column('last_alert_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['alertconfig.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertstate_config_id'), 'alertstate', ['config_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertstate_config_id'), table_name='alertstate')
    op.drop_table('alertstate')
    op.drop_index(op.f('ix_alertconfig_user_id'), table_name='alertconfig')
    op.drop_index(op.f('ix_alertconfig_endpoint_id'), table_name='alertconfig')
    op.drop_table('alertconfig')
    # ### end Alembic commands ###
